b2bserviceapp/src/main/java/com/cfeindia/b2bserviceapp/dto/RefundAmountDto.java
package com.cfeindia.b2bserviceapp.dto;

import java.sql.Timestamp;

import com.cfeindia.b2bserviceapp.util.ExtractorUtil;

public class RefundAmountDto {
	
	private long id;
	private String transid;
	private String retailerId;
	private String retailerMobNo;
	private String retailerName;
	private String mobileNo;
	private String connectionid;
	private String transactionName;
	private String operator;
	private Timestamp createdAt;
	private Timestamp updatedAt;
	private Double amount;
	private double creditAmountFranchisee;
	private String status;
	private Double refundAmount;
	
	private String errorMessage;
	

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getTransid() {
		return transid;
	}

	public void setTransid(String transid) {
		this.transid = transid;
	}

	public String getRetailerId() {
		return retailerId;
	}

	public void setRetailerId(String retailerId) {
		this.retailerId = retailerId;
	}

	public String getRetailerMobNo() {
		return retailerMobNo;
	}

	public void setRetailerMobNo(String retailerMobNo) {
		this.retailerMobNo = retailerMobNo;
	}

	public String getRetailerName() {
		return retailerName;
	}

	public void setRetailerName(String retailerName) {
		this.retailerName = retailerName;
	}

	public String getMobileNo() {
		return mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public String getConnectionid() {
		return connectionid;
	}

	public void setConnectionid(String connectionid) {
		this.connectionid = connectionid;
	}

	public String getTransactionName() {
		return transactionName;
	}

	public void setTransactionName(String transactionName) {
		this.transactionName = transactionName;
	}

	public String getOperator() {
		return operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public Timestamp getCreatedAt() {
		return createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Double getAmount() {
		return amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	public double getCreditAmountFranchisee() {
		return creditAmountFranchisee;
	}

	public void setCreditAmountFranchisee(double creditAmountFranchisee) {
		this.creditAmountFranchisee = creditAmountFranchisee;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Double getRefundAmount() {
		return refundAmount;
	}

	public void setRefundAmount(Double refundAmount) {
		this.refundAmount = refundAmount;
	}

	public String getGeneratedId() {
		return ExtractorUtil.generateIdFromString(retailerId,"R");
	}

	public String getErrorMessage() {
		return errorMessage;
	}

	public void setErrorMessage(String errorMessage) {
		this.errorMessage = errorMessage;
	}

	
	

}

b2bserviceapp/src/main/java/com/cfeindia/b2bserviceapp/franchisee/model/AccountStament.java
package com.cfeindia.b2bserviceapp.franchisee.model;

public class AccountStament {
	
	private String fromDate,
					toDate;
	private String franchiseeid;
	
	private String number;

	public String getFromDate() {
		return fromDate;
	}

	public void setFromDate(String fromDate) {
		this.fromDate = fromDate;
	}

	public String getToDate() {
		return toDate;
	}

	public void setToDate(String toDate) {
		this.toDate = toDate;
	}

	public String getFranchiseeid() {
		return franchiseeid;
	}

	public void setFranchiseeid(String franchiseeid) {
		this.franchiseeid = franchiseeid;
	}

	public String getNumber() {
		return number;
	}

	public void setNumber(String number) {
		this.number = number;
	}
	
}

b2bserviceapp/src/main/java/com/cfeindia/b2bserviceapp/franchisee/model/ActivityHistoryFran.java
package com.cfeindia.b2bserviceapp.franchisee.model;

public class ActivityHistoryFran {
	
	private String fromDate,
					toDate;

	public String getFromDate() {
		return fromDate;
	}

	public void setFromDate(String fromDate) {
		this.fromDate = fromDate;
	}

	public String getToDate() {
		return toDate;
	}

	public void setToDate(String toDate) {
		this.toDate = toDate;
	}
	

}

b2bserviceapp/src/main/java/com/cfeindia/b2bserviceapp/franchisee/model/ChangePasswordFran.java
package com.cfeindia.b2bserviceapp.franchisee.model;

public class ChangePasswordFran {
	
	private String oldPassword,
					newPassword,
					confirmPassword;

	public String getOldPassword() {
		return oldPassword;
	}

	public void setOldPassword(String oldPassword) {
		this.oldPassword = oldPassword;
	}

	public String getNewPassword() {
		return newPassword;
	}

	public void setNewPassword(String newPassword) {
		this.newPassword = newPassword;
	}

	public String getConfirmPassword() {
		return confirmPassword;
	}

	public void setConfirmPassword(String confirmPassword) {
		this.confirmPassword = confirmPassword;
	}
	

}

b2bserviceapp/src/main/java/com/cfeindia/b2bserviceapp/franchisee/model/Datacard.java
package com.cfeindia.b2bserviceapp.franchisee.model;
public class Datacard {
private String category;
private int connectionNumber,amount;
public String getCategory() {
	return category;
}
public void setCategory(String category) {
	this.category = category;
}
public int getConnectionNumber() {
	return connectionNumber;
}
public void setConnectionNumber(int connectionNumber) {
	this.connectionNumber = connectionNumber;
}
public int getAmount() {
	return amount;
}
public void setAmount(int amount) {
	this.amount = amount;
}

	
}

b2bserviceapp/src/main/java/com/cfeindia/b2bserviceapp/franchisee/model/ElectricityBill.java
package com.cfeindia.b2bserviceapp.franchisee.model;

public class ElectricityBill {
	
	private String electricityOperator;

	public String getElectricityOperator() {
		return electricityOperator;
	}

	public void setElectricityOperator(String electricityOperator) {
		this.electricityOperator = electricityOperator;
	}
	
	

}

b2bserviceapp/src/main/java/com/cfeindia/b2bserviceapp/controller/franchisee/ActivityHistoryController.java
package com.cfeindia.b2bserviceapp.controller.franchisee;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.ModelAndView;

import com.cfeindia.b2bserviceapp.franchisee.model.ActivityHistoryFran;

@RequestMapping("/franchisee/**")
@Controller
public class ActivityHistoryController {

	@RequestMapping(value="/activityhistory")
	public ModelAndView activityHistory(){
		
		return new ModelAndView("activityhistory","command",new ActivityHistoryFran());
	}
}

b2bserviceapp/src/main/java/com/cfeindia/b2bserviceapp/controller/franchisee/CashDepositRequestFranController.java
package com.cfeindia.b2bserviceapp.controller.franchisee;

import javax.servlet.http.HttpServletRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;
import com.cfeindia.b2bserviceapp.franchisee.model.CashDepositRequestFran;
import com.cfeindia.b2bserviceapp.franchisee.service.CashDepositRequestFranchiseeService;

@RequestMapping("/franchisee/**")
@Controller
public class CashDepositRequestFranController {
	@Autowired
	CashDepositRequestFranchiseeService cashDepositRequestFranchiseeService;

	@RequestMapping(value="/cashdepositrequestfran")
	public ModelAndView cashDeposit(){
		
		return new ModelAndView("cashdepositrequestfran","command",new CashDepositRequestFran());
	}
	
	@RequestMapping(value="/submitrequest", method=RequestMethod.POST)
	public String submitRequest(@ModelAttribute CashDepositRequestFran cashDepositRequestFran,ModelMap modelMap, HttpServletRequest req)
	{
		String userId=(String)req.getSession().getAttribute("userid");
		try
		{
			
		cashDepositRequestFranchiseeService.saveCashDepositRequest(userId, cashDepositRequestFran);
		modelMap.addAttribute("success","sent your request");
		return "successpagefran";
		}
		catch(Exception e)
		{
			e.printStackTrace();
			return "failure";
		}	
	}
}

b2bserviceapp/src/main/java/com/cfeindia/b2bserviceapp/controller/franchisee/ChangePasswordFranController.java
package com.cfeindia.b2bserviceapp.controller.franchisee;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

import com.cfeindia.b2bserviceapp.franchisee.model.ChangePasswordFran;
import com.cfeindia.b2bserviceapp.service.changepassword.ChangePasswordService;

@RequestMapping("/franchisee/**")
@Controller
public class ChangePasswordFranController {
	
	@Autowired
	ChangePasswordService changePasswordService;
	
	@RequestMapping(value="/changepasswordfran")
	public ModelAndView changePasswordFran(){
		
		return new ModelAndView("changepasswordfran","changepass",new ChangePasswordFran());
	}
	
	@RequestMapping(value="/changepasswordprocessfran",method=RequestMethod.POST)
	public String  changePassword(@ModelAttribute("changepass")ChangePasswordFran changePasswordFran,HttpServletRequest request,ModelMap model) {
		String pathToFollow="changepasswordfran";
		HttpSession session=request.getSession();
		String userID=(String)session.getAttribute("userid");
		long userId=Long.parseLong(userID);
		String oldPassword=changePasswordFran.getOldPassword();
		String newPassword=changePasswordFran.getNewPassword();
		boolean check=changePasswordService.changePassword(oldPassword, newPassword, userId);
		if(check){
			pathToFollow="redirect:successpagefran";
		}
		else{
			model.addAttribute("error", "Pls!Try again");
			}
		return pathToFollow;
	}
	@RequestMapping(value="/successpagefran",method=RequestMethod.GET)
	public String finalPage(ModelMap model){
		model.addAttribute("success", "changed your password");
	return "successpagefran";	
	}

}

b2bserviceapp/src/main/java/com/cfeindia/b2bserviceapp/controller/franchisee/DataCardRechargeController.java
package com.cfeindia.b2bserviceapp.controller.franchisee;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

import com.cfeindia.b2bserviceapp.franchisee.service.FranchiseeInfoService;
import com.cfeindia.b2bserviceapp.recharge.mobile.RechargeTransactionService;
import com.cfeindia.b2bserviceapp.recharge.mobile.dto.FranchiseeInfo;
import com.cfeindia.b2bserviceapp.transport.bean.TransactionTransportBean;

@RequestMapping("/franchisee/**")
@Controller
public class DataCardRechargeController {

	@Autowired
	RechargeTransactionService rechargeTransactionService;
	@Autowired
	private FranchiseeInfoService franchiseeInfoService;

	@RequestMapping(value = "/dataCardrecharge", method = RequestMethod.GET)
	public ModelAndView telecomRecharge() {
		return new ModelAndView("datacardFran", "datacardrecharge",
				new TransactionTransportBean());

	}

	@RequestMapping(value = "/datacardrechargedetail", method = RequestMethod.POST)
	public String rechargeDetail(
			@ModelAttribute("datacardrecharge") TransactionTransportBean transactionTransport,
			ModelMap model, HttpServletRequest req) {
		HttpSession session = req.getSession();
		session.setAttribute("operator", transactionTransport.getOperator());
		session.setAttribute("connectionid",
				transactionTransport.getConnectionid());
		session.setAttribute("amount", transactionTransport.getAmount());

		String pathToFollow = null;

		transactionTransport.setRetailerId((String) req.getSession()
				.getAttribute("userid"));
		transactionTransport.setTransactionName("DATACARD_RECHARGE");
		transactionTransport.setFranchiseeMobileNum((String)session.getAttribute("userName"));
		model.addAttribute("datacardrecharge", transactionTransport);
		try {
			rechargeTransactionService.doRechargeService(transactionTransport);
		} catch (Exception e) {
			e.printStackTrace();
			transactionTransport.setMessage("System Error");
			transactionTransport.setErrorCode(3);
		}

		if (transactionTransport.getErrorCode() > 0) {
			model.addAttribute("Error", transactionTransport.getMessage());
			pathToFollow = "datacardFran";
		} else {
			session.setAttribute("transId", transactionTransport.getTransid());
			// SimpleDateFormat sdf = new
			// SimpleDateFormat("dd-MM-yyyy hh:mm:ss");
			session.setAttribute("datetime",
					transactionTransport.getThirdPartyTransDateTime());
			// model.addAttribute("datetime",
			// sdf.format(transactionTransport.getCreatedAt()));

			String userId = (String) session.getAttribute("userid");
			FranchiseeInfo franchiseeInfo = franchiseeInfoService
					.getFranchiseeInfo(userId);
			session.setAttribute("franchiseeInfo", franchiseeInfo);
			pathToFollow = "redirect:datacardrechargedetail";
		}

		return pathToFollow;
	}

	@RequestMapping(value = "/datacardrechargedetail", method = RequestMethod.GET)
	public String finalPage(ModelMap model) {
		model.addAttribute("Message", "Recharge Successful");
		return "datacardrechargedetail";
	}

}

b2bserviceapp/src/main/java/com/cfeindia/b2bserviceapp/controller/franchisee/DthTvRechargeController.java
package com.cfeindia.b2bserviceapp.controller.franchisee;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

import com.cfeindia.b2bserviceapp.franchisee.service.FranchiseeInfoService;
import com.cfeindia.b2bserviceapp.recharge.mobile.RechargeTransactionService;
import com.cfeindia.b2bserviceapp.recharge.mobile.dto.FranchiseeInfo;
import com.cfeindia.b2bserviceapp.transport.bean.TransactionTransportBean;

@RequestMapping("/franchisee/**")
@Controller
public class DthTvRechargeController {

	@Autowired
	RechargeTransactionService rechargeTransactionService;

	@Autowired
	private FranchiseeInfoService franchiseeInfoService;

	@RequestMapping(value = "/tvrecharge", method = RequestMethod.GET)
	public ModelAndView DThtvRecharge() {
		return new ModelAndView("dthtvFran", "dthtv",
				new TransactionTransportBean());

	}

	@RequestMapping(value = "/rechargedetaildth", method = RequestMethod.POST)
	public String dthrechargeDetail(
			@ModelAttribute("dthtv") TransactionTransportBean transactionTransport,
			ModelMap model, HttpServletRequest req) {
		HttpSession session = req.getSession();
		session.setAttribute("rechargeType",
				transactionTransport.getRechargeType());
		session.setAttribute("type", transactionTransport.getType());
		session.setAttribute("operator", transactionTransport.getOperator());
		session.setAttribute("amount", transactionTransport.getAmount());
		session.setAttribute("connectionid",
				transactionTransport.getConnectionid());

		String pathToFollow = null;

		transactionTransport.setRetailerId((String) req.getSession()
				.getAttribute("userid"));
		transactionTransport.setTransactionName("DTH_RECHARGE");
		transactionTransport.setFranchiseeMobileNum((String) session
				.getAttribute("userName"));

		model.addAttribute("dthtv", transactionTransport);
		try {
			rechargeTransactionService.doRechargeService(transactionTransport);
		} catch (Exception e) {
			e.printStackTrace();
			transactionTransport.setMessage("System Error");
			transactionTransport.setErrorCode(3);
		}

		if (transactionTransport.getErrorCode() > 0) {
			model.addAttribute("Error", transactionTransport.getMessage());
			pathToFollow = "dthtvFran";
		} else {
			session.setAttribute("transId", transactionTransport.getTransid());
			// SimpleDateFormat sdf = new
			// SimpleDateFormat("dd-MM-yyyy hh:mm:ss");
			session.setAttribute("datetime",
					transactionTransport.getThirdPartyTransDateTime());
			// model.addAttribute("datetime",
			// sdf.format(transactionTransport.getCreatedAt()));
			String userId = (String) session.getAttribute("userid");
			FranchiseeInfo franchiseeInfo = franchiseeInfoService
					.getFranchiseeInfo(userId);
			session.setAttribute("franchiseeInfo", franchiseeInfo);
			pathToFollow = "redirect:rechargedetaildth";
		}

		return pathToFollow;
	}

	@RequestMapping(value = "/rechargedetaildth", method = RequestMethod.GET)
	public String finalPage(ModelMap model) {
		model.addAttribute("Message", "Recharge Successful");
		return "rechargedetaildth";
	}

	public RechargeTransactionService getdoRechargeTransactionService() {
		return rechargeTransactionService;
	}

	public void setdoRechargeTransactionService(
			RechargeTransactionService rechargeTransactionService) {
		this.rechargeTransactionService = rechargeTransactionService;
	}
}

b2bserviceapp/src/main/webapp/WEB-INF/views/franchisee/accountstatement.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>


<link rel="stylesheet"
	href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css" />

<script type="text/javascript">
	$(function() {
		$("#fromdate").datepicker();
	});
	$(function() {
		$("#todate").datepicker();
	});
	function addTable() {
		document.getElementById('table').innerHTML;
		return false;
	}
</script>
<div id="search_panel1">
	<h1>Account Statement</h1>
	<form:form method="post" action="accountstatementretrieve"
		modelAttribute="accountstatement">
		<div class="search_panel_box">
			<div class="form_row">
				<label>From Date</label>
				<form:input class="inputfield" required="required" path="fromDate"
					type="text" id="fromdate"></form:input>
			</div>
			<div class="form_row">
				<label>To Date</label>
				<form:input class="inputfield" required="required" path="toDate"
					type="text" id="todate"></form:input>
			</div>

		</div>

		<input type="submit" class="button" value="View" />
	</form:form>
</div>
<div id="table">
	<c:if test="${not empty reportList }">
		<table border="1" width="100%">
			<tr bgcolor="#3399FF">
				<td><strong>SN.</strong></td>
				<td><strong>DATE/TIME</strong></td>
				<td><strong>PARTICULARS</strong></td>
				<td><strong>TID</strong></td>
				<td><strong>TYPE</strong></td>
				<td><strong>AMOUNT</strong></td>
				<td><strong>BALANCE</strong></td>
			</tr>
			<c:forEach items="${reportList}" var="reportItem" varStatus="status">
				<tr>
					<td>${status.count}</td>
					<td>${reportItem.createdAt}</td>
					<td>${reportItem.particulars}</td>
					<td>${reportItem.transactionId}</td>
					<td>${reportItem.transactionType}</td>
					<td>Rs.${reportItem.displayAmount}</td>
					<td>Rs.${reportItem.newB2bCurrBal}</td>
					
				</tr>
			</c:forEach>
		</table>
	</c:if>
</div>

b2bserviceapp/src/main/webapp/WEB-INF/views/franchisee/cashrequestsprocessfran.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>


<h2>CASH DEPOSIT REQUESTS</h2>
<form action="showallcashdepositrequestsdist" method="get">
<input class="button" type="submit" value="show all">
</form>
<div id="table">
	<c:if test="${not empty depositrequestlist }">
		<table border="1" width="100%">
			<tr bgcolor="#3399FF">
				<td><strong>SN.</strong></td>					
				<td><strong>REQ. TYPE</strong></td>
				<td><strong>PAYMENT MODE</strong></td>
				<td><strong>AMOUNT</strong></td>
				<td><strong>BANK</strong></td>							
				<td><strong>RECIEPT NO.</strong></td>
				<td><strong>DATE</strong></td>
				<td><strong>REMARK</strong></td>
				<td><strong>TRANSFER</strong></td>
			</tr>
			<c:forEach items="${depositrequestlist}" var="requestItem" varStatus="status">
				<tr>
				<form action="showTransferPage" method="POST">
					<td>${status.count}</td>
					<td>${requestItem.requestType}</td>
					<td>${requestItem.paymentMode}</td>
					<td>RS.${requestItem.amount}0</td>
					<td>${requestItem.counter}</td>
					<td>${requestItem.recieptChequeDdNo}</td>					
					<td>${requestItem.chequeDdDate}</td>
					<td>${requestItem.remark}</td>
					<td>
						<input type="hidden" name="amount" value="${requestItem.amount}">
						<input type="hidden" name="id" value="${requestItem.id}">
						<input type="hidden" name="requesterId" value="${requestItem.requesterId}">
						<input class="button" type="submit" value="transfer">
					</td>
				</form>
				</tr>
			</c:forEach>
		</table>
	</c:if>
</div>

b2bserviceapp/src/main/webapp/WEB-INF/views/franchisee/changepasswordfran.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>

<script type="text/javascript">

function checkPassword(){
	
	var newpass=document.getElementById("newPassword").value;
	var confirmpass=document.getElementById("confirmPassword").value;
	if(newpass==confirmpass){
		
		return true;
	}
	else{
		alert("New & confirm password must be same");
		document.getElementById("confirmPassword").focus();
		return false;
	}
	
	
}
    </script>
<div id="search_panel1">
        <h1>Change Password</h1>
        <h4>${error}</h4>
        <form:form method="post" action="changepasswordprocessfran"  onSubmit="return checkPassword();" modelAttribute="changepass">
          <div class="search_panel_box">
            
            <div class="form_row">
          <label>Old Password</label>
          <form:password class="inputfield" required="required" path="oldPassword" id="oldPassword"></form:password>
        </div>
            
            <div class="form_row">
          <label>New Password</label>
          <form:password class="inputfield" required="required" path="newPassword"  id="newPassword"></form:password>
        </div>
        
           <div class="form_row">
          <label>Confirm Password</label>
          <form:password class="inputfield" required="required" path="confirmPassword" id="confirmPassword"></form:password>
        </div>
            
          </div>
    
            <input type="submit" required="required" class="button" value="Change"/>
         
        </form:form>
      </div>

 
 

b2bserviceapp/src/main/webapp/WEB-INF/views/franchisee/refundrequest.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<div id="search_panel1">
	<h1>Refund Request</h1>
		<h2>${error}</h2>
	<form:form method="POST" action="refundrequestfran">
		<div class="search_panel_box">
			<div class="form_row">
				<label>Transaction ID</label> <input class="inputfield" name="tid"
					type="text" id="transId" />
			</div>
			<input type="submit" class="button" value="Submit" />
		</div>
	</form:form>
</div>
<div style="padding-left: 130px">
	<c:if test="${not empty detailForRefund }">
		<div style="padding-left: 50px">
			<h1>Transaction Details</h1>
		</div>
		<form:form method="post" action="refundamount">
			<table>
				<c:forEach items="${detailForRefund}" var="refund"
					varStatus="status">
					<tr>
						<td align="right"><strong>RETAILER ID : </strong></td>
						<td align="left">${refund.generatedId}</td>
					</tr>
					<tr>
						<td align="right"><strong>RETAILER MOBILE No. : </strong></td>
						<td align="left">${refund.retailerMobNo}</td>
					</tr>
					<tr>
						<td align="right"><strong>RETAILER NAME : </strong></td>
						<td align="left">${refund.retailerName}</td>
					</tr>
					<tr>
						<td align="right"><strong>MOBILE/CONNECTION No. : </strong></td>
						<td align="left">${refund.mobileNo}${refund.connectionid}</td>
					</tr>
					<tr>
						<td align="right"><strong>RECHARGE TYPE : </strong></td>
						<td align="left">${refund.transactionName}</td>
					</tr>
					<tr>
						<td align="right"><strong>OPERATOR : </strong></td>
						<td align="left">${refund.operator}</td>
					</tr>
					<tr>
						<td align="right"><strong>DATE/TIME : </strong></td>
						<td align="left"><strong></strong>${refund.createdAt}</td>
					</tr>
					<tr>
						<td align="right"><strong>CREDIT AMOUNT : </strong></td>
						<td align="left">Rs.${refund.creditAmountFranchisee}</td>
					</tr>
					<tr>
						<td align="right"><strong>AMOUNT : </strong></td>
						<td align="left">Rs.${refund.amount}</td>
					</tr>
					<tr>
						<td align="right"><strong>STATUS : </strong></td>
						<td align="left">${refund.status}</td>
					</tr>
					<input type="hidden" name="id" value="${refund.id}">
					<input type="hidden" name="franId" value="${refund.retailerId}">
					<input type="hidden" name="amount" value="${refund.amount}">
					<input type="hidden" name="creditAmount"
						value="${refund.creditAmountFranchisee}">
					<input type="hidden" name="status" value="${refund.status}">
					<tr>
						<td colspan="2" align="center"><br /> <input type="submit"
							class="button" value="Refund" /></td>
					</tr>
				</c:forEach>

			</table>

		</form:form>
	</c:if>
</div>

b2bserviceapp/src/main/webapp/WEB-INF/views/franchisee/welcomeFran.jsp
  
    <div id="search_panel1">
     
        <h1>Welcome ${franchiseeInfo.name}</h1>
      	<div class="form_row">
			<div class="tdElement1"><h4>B2B Balance:</h4></div>
            <div class="tdElement1"><h4>Rs. ${franchiseeInfo.b2bCurrentBalance}</h4></div>
		</div>
       <div class="form_row">
			<div class="tdElement1"><h4>B2B Ad Unit Balance:</h4></div>
            <div class="tdElement1"><h4>Rs. ${franchiseeInfo.b2bCurrentAdUnitBalance}</h4></div>
		</div>
 	
    </div>


  